version: '3.3'
services:

  wordpress:
    # depends_on:
    #   - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: awesome_password
    volumes:
      - .:/var/www/html

volumes:
  .:

